spring.application.name=CRM

#spring.datasource.url=jdbc:mysql://localhost:3306/db_crm
#spring.datasource.username=root
#spring.datasource.password=Manager
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#spring.app.jwtSecret=mySecretKey123912738hgdtehygsferdtrgfyhgnww
#spring.app.jwtExpirationMs=300000000
#
##Spring Mail Properties
#spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
#spring.mail.port=${SPRING_MAIL_PORT:587}
#spring.mail.username=${SPRING_MAIL_USERNAME:your-email@gmail.com}
#spring.mail.password=${SPRING_MAIL_PASSWORD:your-app-password}
#
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=5000
#spring.mail.properties.mail.smtp.writetimeout=5000
#
## Application Mail Sender Default
#app.mail.from=${APP_MAIL_FROM:${SPRING_MAIL_USERNAME}}
#
## Thymeleaf Mail Template Configuration
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.mode=HTML
#spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.cache=false
#
#
##Scheduling notification
#crm.followup.scheduler.cron=0 30 09 * * MON-SAT
#crm.notification.cleanup.cron=0 0 2 * * *
#crm.resignation.scheduler.cron=0 0 1 * * *

#ai.service.api-key=${AI_SERVICE_API_KEY}
#email.service.base-url=${EMAIL_SERVICE_BASE_URL}